[package]
name    = "ohkami_worker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"

[features]
DEBUG = ["dep:console_error_panic_hook"]

[dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }

ohkami = { git = "https://github.com/kana-rus/ohkami.git", features = ["rt_worker"] }
worker = { version = "0.3.0" }

yarte        = { version = "0.15.7" }
wasm-bindgen = { version = "0.2.92" }
